In [1]:
% cd ../..

C:\Users\cbcastleberry\Documents\GitHub\kaggle_talkdata

In [2]:
import pandas as pd
import pickle
import os
import gc
import src.features.build_computed_features as build_features

In [3]:
pd.options.display.max_columns = 100

In [4]:
train_path = os.path.join('.', 'data', 'raw', 'train.csv')

In [5]:
dtypes = {
        'ip'            : 'uint32',
        'app'           : 'uint16',
        'device'        : 'uint16',
        'os'            : 'uint16',
        'channel'       : 'uint16',
        'is_attributed' : 'uint8',
        'click_id'      : 'uint32'
        }

cols = ['ip', 'app', 'device', 'os', 'channel', 'click_time']

In [6]:
train_df = pd.read_csv(train_path, usecols=cols, dtype=dtypes, nrows=10000, parse_dates=['click_time'])

In [7]:
train_df.head()

       ip  app  device  os  channel          click_time
0   83230    3       1  13      379 2017-11-06 14:32:21
1   17357    3       1  19      379 2017-11-06 14:33:34
2   35810    3       1  13      379 2017-11-06 14:34:12
3   45745   14       1  13      478 2017-11-06 14:34:52
4  161007    3       1  13      379 2017-11-06 14:35:08

In [8]:
new_df, predictors, categorical, target = build_features.transform_data(train_df=train_df)

Extracting new features...
Counting unqiue  channel  by  ['ip'] ...
X0 max value =  39
Cumulative count by  ['ip', 'device', 'os'] ...
X1 max value =  18
Counting unqiue  hour  by  ['ip', 'day'] ...
X2 max value =  3
Counting unqiue  app  by  ['ip'] ...
X3 max value =  18
Counting unqiue  os  by  ['ip', 'app'] ...
X4 max value =  8
Counting unqiue  device  by  ['ip'] ...
X5 max value =  4
Counting unqiue  channel  by  ['app'] ...
X6 max value =  23
Cumulative count by  ['ip'] ...
X7 max value =  64
Counting unqiue  app  by  ['ip', 'device', 'os'] ...
X8 max value =  11
Aggregating by  ['ip', 'day', 'hour'] ...
ip_tcount max value =  65
Aggregating by  ['ip', 'app'] ...
ip_app_count max value =  16
Aggregating by  ['ip', 'app', 'os'] ...
ip_app_os_count max value =  13
Calculating variance of  hour  by  ['ip', 'day', 'channel'] ...
ip_tchan_count max value =  0.5
Calculating variance of  hour  by  ['ip', 'app', 'os'] ...
ip_app_os_var max value =  2.0
Calculating variance of  day  by  ['ip', 'app', 'channel'] ...
ip_app_channel_var_day max value =  0.0
Calculating mean of  hour  by  ['ip', 'app', 'channel'] ...
ip_app_channel_mean_hour max value =  16.0
doing nextClick
vars and data type:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 9999
Data columns (total 25 columns):
ip                          10000 non-null uint32
app                         10000 non-null uint16
device                      10000 non-null uint16
os                          10000 non-null uint16
channel                     10000 non-null uint16
hour                        10000 non-null uint8
day                         10000 non-null uint8
X0                          10000 non-null uint8
X1                          10000 non-null uint32
X2                          10000 non-null uint8
X3                          10000 non-null uint8
X4                          10000 non-null uint8
X5                          10000 non-null uint16
X6                          10000 non-null uint32
X7                          10000 non-null uint32
X8                          10000 non-null uint32
ip_tcount                   10000 non-null uint32
ip_app_count                10000 non-null uint32
ip_app_os_count             10000 non-null uint16
ip_tchan_count              10000 non-null float32
ip_app_os_var               10000 non-null float32
ip_app_channel_var_day      10000 non-null float32
ip_app_channel_mean_hour    10000 non-null float32
nextClick                   10000 non-null float32
nextClick_shift             10000 non-null float32
dtypes: float32(6), uint16(6), uint32(7), uint8(6)
memory usage: 761.7 KB
predictors ['nextClick', 'nextClick_shift', 'app', 'device', 'os', 'channel', 'hour', 'day', 'ip_tcount', 'ip_tchan_count', 'ip_app_count', 'ip_app_os_count', 'ip_app_os_var', 'ip_app_channel_var_day', 'ip_app_channel_mean_hour', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8']

In [9]:
new_df.head()

,ip,app,device,os,channel,hour,day,X0,X1,X2,X3,X4,X5,X6,X7,X8,ip_tcount,ip_app_count,ip_app_os_count,ip_tchan_count,ip_app_os_var,ip_app_channel_var_day,ip_app_channel_mean_hour,nextClick,nextClick_shift
0,83230,3,1,13,379,14,6,1,0,1,1,1,1,23,0,1,1,1,1,0.0,0.0,0.0,14.0,1.490021e+09,0.000000e+00
1,17357,3,1,19,379,14,6,1,0,2,1,2,1,23,0,1,1,2,1,0.5,0.0,0.0,14.5,1.490021e+09,1.490021e+09
2,35810,3,1,13,379,14,6,1,0,1,1,1,1,23,0,1,1,1,1,0.0,0.0,0.0,14.0,1.490021e+09,1.490021e+09
3,45745,14,1,13,478,14,6,14,0,2,6,2,1,15,0,4,1,3,2,0.0,2.0,0.0,14.0,5.110000e+03,1.490021e+09
4,161007,3,1,13,379,14,6,1,0,1,1,1,1,23,0,1,1,1,1,0.0,0.0,0.0,14.0,1.490021e+09,5.110000e+03

In [10]:
predictors

['nextClick',
 'nextClick_shift',
 'app',
 'device',
 'os',
 'channel',
 'hour',
 'day',
 'ip_tcount',
 'ip_tchan_count',
 'ip_app_count',
 'ip_app_os_count',
 'ip_app_os_var',
 'ip_app_channel_var_day',
 'ip_app_channel_mean_hour',
 'X0',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X7',
 'X8']

In [11]:
target

'is_attributed'

In [12]:
categorical

['app', 'device', 'os', 'channel', 'hour', 'day']

In [13]:
?build_features.transform_data